### ISSUE TITLE
请问可以支持MIPC251-4吗？

### ISSUE THREAD

**Issue by spacex-3** [likaci/mercury-ipc-control#1]
我在论坛看到有其他大佬调整了rsa部分，但是我依旧报错。
https://bbs.hassbian.com/thread-9873-1-1.html

麻烦大佬帮忙调整至可以支持251-4，感激不尽！

谢谢！！

**Comment by spacex-3** [comment]
更新论坛大佬的mipcc.py后运行您的代码报错内容一样：

Traceback (most recent call last):
  File "mipcc.py", line 34, in <module>
    stok = get_stok(base_url, username, password)
  File "mipcc.py", line 19, in get_stok
    key = result['stok']
KeyError: 'stok'

**Comment by ruoleng** [comment]
请问，知道App上直接看摄像头的端口吗？内网穿透后想App看，但是一直失败
